apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodapp
  labels:
    app: foodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodapp
  template:
    metadata:
      labels:
        app: foodapp
    spec:
      containers:
      - name: foodapp
        image: darshanbk812/online-food-delivery-system:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: foodapp-service
spec:
  selector:
    app: foodapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
